/********************************************************************
* /home/yuxip/FMS/CellScan/src/MyCellMgrDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/yuxip/FMS/CellScan/src/MyCellMgrDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMyCellMgrDict();
extern void G__cpp_setup_inheritanceMyCellMgrDict();
extern void G__cpp_setup_typetableMyCellMgrDict();
extern void G__cpp_setup_memvarMyCellMgrDict();
extern void G__cpp_setup_globalMyCellMgrDict();
extern void G__cpp_setup_memfuncMyCellMgrDict();
extern void G__cpp_setup_funcMyCellMgrDict();
extern void G__set_cpp_environmentMyCellMgrDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MyCellMgr.h"
#include "MyCell.h"
#include "MyCellRunDep.h"
#include "MyCellEvt.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MyCellMgrDictLN_TClass;
extern G__linked_taginfo G__MyCellMgrDictLN_TBuffer;
extern G__linked_taginfo G__MyCellMgrDictLN_TDirectory;
extern G__linked_taginfo G__MyCellMgrDictLN_TMemberInspector;
extern G__linked_taginfo G__MyCellMgrDictLN_TObject;
extern G__linked_taginfo G__MyCellMgrDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__MyCellMgrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MyCellMgrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TObjArray;
extern G__linked_taginfo G__MyCellMgrDictLN_TString;
extern G__linked_taginfo G__MyCellMgrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TFile;
extern G__linked_taginfo G__MyCellMgrDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__MyCellMgrDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TCut;
extern G__linked_taginfo G__MyCellMgrDictLN_MyCell;
extern G__linked_taginfo G__MyCellMgrDictLN_MyCellRunDep;
extern G__linked_taginfo G__MyCellMgrDictLN_MyCellEvt;
extern G__linked_taginfo G__MyCellMgrDictLN_CalibStr;
extern G__linked_taginfo G__MyCellMgrDictLN_Geom;
extern G__linked_taginfo G__MyCellMgrDictLN_TTree;
extern G__linked_taginfo G__MyCellMgrDictLN_MyCellMgr;
extern G__linked_taginfo G__MyCellMgrDictLN_TH1F;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__MyCellMgrDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MyCellMgrDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__MyCellMgrDictLN_TH2F;
extern G__linked_taginfo G__MyCellMgrDictLN_TGraph;

/* STUB derived class for protected member access */
